# Generated by Django 2.1.2 on 2018-11-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Client ID')),
                ('client_name', models.CharField(max_length=14, verbose_name='Client Name')),
                ('client_address', models.CharField(default='', max_length=140, verbose_name='Address')),
                ('client_email_address', models.CharField(default='', max_length=140, verbose_name='Client Email')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='munshai.Client', verbose_name='client')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(default='', max_length=140, verbose_name='Document Name')),
                ('document_type', models.CharField(default='', max_length=140, verbose_name='Document Name')),
                ('client_id', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='munshai.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'documents',
            },
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='document',
            field=models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, to='munshai.Document', verbose_name='document'),
        ),
    ]
