# Generated by Django 2.1.2 on 2018-11-07 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('munshai', '0002_remove_document_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client_id',
            field=models.ForeignKey(db_column='client_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='munshai.Client', verbose_name='client'),
            preserve_default=False,
        ),
    ]
