# Generated by Django 2.1.2 on 2018-11-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_merge'),
        ('munshai', '0004_auto_20181107_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelloWorldProcess',
            new_name='DocumentUploadProcess',
        ),
    ]
